### ISSUE TITLE
Loading Litematic Schematic with negative position value causes InvalidValue Error instead successful load

### ISSUE THREAD

**Issue by HafiTheCat** [RubixDev/rustmatica#5]
# Actual Behavior
Loading a schematic with negative `Position x` value in the following way

```rust
fn main() {
    let res = rustmatica::Litematic::read_file("Supercharged_contained_shulker_farm.litematic");
    dbg!(res);
}
```

will result in the following error:

```rust
Err(
    NBT(
        Error(
            "invalid value: integer `-31`, expected usize",
        ),
    ),
)
```

# Expected Behavior
Loading a schematic with negative `Position x` value will result in a successful load of the schematic

# Steps to Reproduce the Problem
Load any schematic (or used test file below) that contains a negative `Position x` value.

# Sidenote
I already mentioned this issue on a repo for a similar crate, which can be inspected here: SlopeCraft/mc_schem#1
The individual size values can also be negative, as can be seen by inspecting the attached schematic.

# Specifications
## Rust specifications
Rustc version: rustc 1.76.0 (07dca489a 2024-02-04)
Toolchain: stable-x86_64-unknown-linux-gnu (default)

## Schematic specifications
This `.litematic` was generated by the litematica mod, minecraft version `minecraft 1.20.4`.
Type: LITEMATIC
MinecraftDataVersion: 3465
Subversion: 1
Version: 6
Regions: 1

[testSchematic.zip](https://github.com/RubixDev/rustmatica/files/15108232/testSchematic.zip)

**Comment by RubixDev** [comment]
Fixed in v0.2.0. [This](https://github.com/maruohon/litematica/issues/53) is about all the documentation on the litematica format, which doesn't really specify much, so I just thought it'd always be positive. But you're right. [Looking at the code](https://github.com/maruohon/litematica/blob/d8bc8745c6c95efa2bb1b88e726dc394847b0724/src/main/java/fi/dy/masa/litematica/schematic/LitematicaSchematic.java#L100-L101), both the region sizes and positions use `BlockPos` which can indeed be negative.
